algoritmo "p"


var
v : caracter
n : inteiro

inicio

enquanto v <> "n" faca

   escreva ("Digite um numero: ")
   leia (n)
   se n>0 entao
      escreval (" O numero e positivo")
   senao
      se n<0 entao
         escreval (" O numero e negativo")
      senao
         escreval (" O numero e 0")
      fimse
   fimse
escreval (" ")
Escreva (" Deseja continuar | S- Sim | N- Não | ")
leia (v)
escreval (" ")
limpatela

fimenquanto

fimalgoritmo
