algoritmo "funcMedia"

var
n1,n2,n3:inteiro
m: caractere

funcao mediaA(n1f,n2f,n3f: inteiro):inteiro

var

inicio

fimfuncao

funcao mediaA(n1f,n2f,n3f: inteiro):inteiro

var

inicio

fimfuncao

inicio

escreval("Digite a primeria nota")
leia(n1)
escreval("Digite a primeria nota")
leia(n2)
escreval("Digite a primeria nota")
leia(n3)
escreval("Digite A para media Aritmetica ")
escreval("Digite P para media Ponderada ")
leia(m)

fimalgoritmo
