Algoritmo "s"



Var



v: vetor[1..6] de inteiro

c: inteiro

Inicio



para c de 1 ate 6 faca

     escreva ("Digite o", c, "º numero: ")

              leia (v[c])

fimpara

escreval("Vetor inicial")

para c de 1 ate 6 faca

     escreva (c)

fimpara

escreval (" ")

escreval("Vetor final")

para c de 6 ate 1 passo -1 faca

     escreva (c)

fimpara





Fimalgoritmo